export const FACTURA_ADD_ITEM = 'FACTURA_ADD_ITEM';
export const FACTURA_REMOVE_ITEM = 'FACTURA_REMOVE_ITEM';
export const FACTURA_SAVE_SHIPPING = 'FACTURA_SAVE_SHIPPING';
export const FACTURA_SAVE_PAYMENT = 'FACTURA_SAVE_PAYMENT';